server:
  port: 80
  servlet:
    context-path: /mike
    session:
      timeout: 60    #单位秒
      cookie:
        name: myLove
  tomcat:
    max-connections: 20000
    max-threads: 400
    
spring:
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
     
        